.github/workflows/cmake.yml, CMakeLists.txt, src/overlaybd/fs/lsmt/CMakeLists.txt, src/overlaybd/fs/lsmt/test/lsmt-filetest.h, src/overlaybd/fs/lsmt/test/test.cpp, src/overlaybd/fs/zfile/CMakeLists.txt, src/overlaybd/fs/zfile/test/test.cpp
=> add test for lsmt/zfile and add CMake workflow

CMakeLists.txt, README.md
=> DOC: update readme.md, update cmake project name

README.md
=> DOC: add install from packages

README.md, src/scsi_helper.cpp
=> doc: update requirements

src/image_file.cpp, src/overlaybd/fs/lsmt/file.cpp
=> overlaybd: larger parallelism for open and load index

README.md, src/CMakeLists.txt, src/example_config/overlaybd-tcmu.service, src/main.cpp
=> overlaybd-tcmu systemd service

src/overlaybd/fs/lsmt/file.cpp
=> Overlaybd: ensure to get the correct blksize

CMake/externalBoost.cmake
=> Fix boost download URL

.github/workflows/dco.yml, CONTRIBUTING.md, README.md
=> Add contributing doc and DCO checker workflow 

src/overlaybd/fs/registryfs/registryfs.cpp
=> Attempt access_token if missing token in auth

.github/workflows/cmake.yml, src/overlaybd/CMakeLists.txt, src/overlaybd/fs/CMakeLists.txt, src/overlaybd/fs/cache/frontend/cached_file.cpp, src/overlaybd/fs/cache/full_file_cache/CMakeLists.txt, src/overlaybd/fs/cache/full_file_cache/test/CMakeLists.txt, src/overlaybd/fs/cache/full_file_cache/test/cache_test.cpp, src/overlaybd/fs/cache/full_file_cache/test/random_generator.h, src/overlaybd/fs/lsmt/test/CMakeLists.txt, src/overlaybd/fs/test/CMakeLists.txt, src/overlaybd/fs/test/mock.h, src/overlaybd/fs/test/test.cpp, src/overlaybd/fs/test/test_throttledfile.cpp, src/overlaybd/fs/zfile/test/CMakeLists.txt, src/overlaybd/photon/CMakeLists.txt, src/overlaybd/photon/test/CMakeLists.txt, src/overlaybd/photon/test/signalfdtest.cpp, src/overlaybd/photon/test/test-syncio.cpp, src/overlaybd/photon/test/test.cpp, src/overlaybd/test/CMakeLists.txt, src/overlaybd/test/test.cpp, src/overlaybd/test/test_scalepool.cpp
=> Add unit tests

src/example_config/overlaybd-tcmu.service
=> Service: support auto restart

src/CMakeLists.txt, src/config.h, src/example_config/overlaybd.json, src/image_file.cpp, src/image_file.h, src/main.cpp, src/prefetch.cpp, src/prefetch.h
=> Add trace prefetch feature

src/prefetch.cpp
=> Fix prefetch dump: detect thread must be interrupted, in order to protect dump

src/main.cpp
=> tcmulit_close in new kernel thread to avoid hang

src/bk_download.cpp
=> fix close fd after sha256 verification for background download

src/overlaybd/fs/zfile/zfile.cpp, src/prefetch.cpp, src/switch_file.cpp
=> Add ownership to PrefetchFile

.clang-format, src/overlaybd/fs/localfs.cpp, src/overlaybd/fs/lsmt/file.cpp, src/overlaybd/fs/lsmt/index.cpp, src/overlaybd/fs/lsmt/index.h, src/overlaybd/fs/lsmt/test/lsmt-filetest.h, src/overlaybd/fs/lsmt/test/test.cpp
before: RW | layer0 | layer1 | ... | layerN
now:    layer0 | layer1 | ... | layerN | RW
Signed-off-by: bigvan <tuji.yyf@alibaba-inc.com>
=> Reorder LSMTFile::m_files[].

README.md
=> DOC: add kernel module description

README.md, src/overlaybd/fs/cache/frontend/cached_file.cpp, src/overlaybd/fs/cache/full_file_cache/cache_store.cpp, src/overlaybd/fs/cache/full_file_cache/cache_store.h, src/overlaybd/fs/cache/pool_store.h, src/overlaybd/utility.h
=> fix full file cache on xfs and fix typo

.github/workflows/cmake.yml
Add DSA build package
Signed-off-by: Haibin Huang <haibin.huang@intel.com>
=> Add DSA build package

CMakeLists.txt, src/image_service.cpp
=> bump version to 0.4.1 and fix log size

src/overlaybd/fs/tar_file.cpp
Signed-off-by: liulanzheng <liulanzheng@gmail.com>
=> compatible with none-tar overlaybd blobs

src/overlaybd/fs/tar_file.cpp, src/overlaybd/fs/zfile/test/test.cpp, src/tools/overlaybd-info.cpp, src/tools/overlaybd-zfile.cpp
=> Fix read tar-header for huge file (>8Gib)

src/overlaybd/fs/cache/full_file_cache/cache_pool.cpp, src/overlaybd/fs/cache/full_file_cache/test/cache_test.cpp
to share cache cross repo #80 
Signed-off-by: liulanzheng <liulanzheng@gmail.com>
=> cache: store files in one directory identified by digest

README.md, src/overlaybd/fs/cache/ocf_cache/CMakeLists.txt
add ocf config to README and adjust ocf test in CMakeLists.txt
=> add ocf config to README

src/overlaybd/fs/zfile/zfile.cpp
=> Fix alog format error in ZFile.cpp

src/overlaybd/fs/lsmt/file.cpp
=> lsmt fix rw_tag for sparse file

src/overlaybd/zfile/CMakeLists.txt, src/overlaybd/zfile/README.md, src/overlaybd/zfile/compressor.cpp, src/overlaybd/zfile/compressor.h, src/overlaybd/zfile/crc32/crc32c.cpp, src/overlaybd/zfile/lz4/lz4-qat.c, src/overlaybd/zfile/lz4/lz4-qat.h, src/overlaybd/zfile/zfile.cpp
Accelerate compression to provide improved efficiency, scalability and
performance. Intel QuickAssist Technology (Intel QAT) offloading
Compression from CPU which can save cycles, time and space.
As the complexity of applications continues to grow, systems need more
and more computational resources for workloads, including cryptography
and data compression.
The drivers and patches offered here assist application developers to
take advantage of Intel® QuickAssist Integrated Accelerator that is
offered with platforms based on Intel® processors.
To Learn how to use Intel® QuickAssist Technology and run example code,
review our tutorial videos on Intel Developer Zone – Intel® QuickAssist
Technology Technical Getting Started Tutorials -
https://software.intel.com/en-us/networking/quickassist …
=> Framework for accelerating compression using QAT

README.md, src/overlaybd/zfile/compressor.cpp
Signed-off-by: Siwei Qin <siwei.qin@intel.com>
Co-Authored-By: Haibin Huang <haibin.huang@intel.com>
Co-Authored-By: Siwei Qin <siwei.qin@intel.com>
=> Add cmake option for QAT

MAINTAINERS
=> Add maintainer list

MAINTAINERS
#104 
hi~ @fuweid ,
@beef9999 and @hhb584520 have been making a lot of high-level features in overlaybd including IO trace prefetching/OCF cache/Intel DSA hardware supports.
https://github.com/containerd/overlaybd/commits?author=beef9999
https://github.com/containerd/overlaybd/commits?author=hhb584520
I would like to invite them as reviewers :D
=> MAINTAINERS: add beef9999 and hhb584520 as Reviewers

src/config.h, src/example_config/overlaybd.json, src/image_service.cpp
=> add p2pconfig

.github/workflows/cmake.yml, src/example_config/redis.obd.config.json
=> CI: add e2e test

README.md, src/image_service.cpp, src/overlaybd/registryfs/registryfs.cpp, src/overlaybd/registryfs/registryfs.h
=> Add p2p support

CMake/Findphoton.cmake, CMakeLists.txt, README.md
=> update photon to v0.3.0

src/tools/overlaybd-zfile.cpp
=> fix zfile tool description

CMake/Findphoton.cmake, CMakeLists.txt, src/CMakeLists.txt, src/image_service.cpp, src/image_service.h, src/main.cpp, src/overlaybd/CMakeLists.txt, src/overlaybd/cache/frontend/cached_fs.cpp, src/overlaybd/cache/full_file_cache/test/cache_test.cpp, src/overlaybd/cache/ocf_cache/ocf_cache.cpp, src/overlaybd/cache/ocf_cache/test/ocf_perf_test.cpp, src/overlaybd/lsmt/test/test.cpp, src/overlaybd/registryfs/registryfs.cpp, src/overlaybd/tar_file.cpp, src/overlaybd/untar/CMakeLists.txt, src/overlaybd/untar/header.cpp, src/overlaybd/untar/libtar.cpp, src/overlaybd/untar/libtar.h, src/overlaybd/untar/test/CMakeLists.txt, src/overlaybd/untar/test/test.cpp, src/overlaybd/untar/test2/CMakeLists.txt, src/overlaybd/untar/test2/main.cpp, src/overlaybd/untar/whiteout.cpp, src/overlaybd/zfile/test/test.cpp
sync photon;
add untar with whiteout support;
support custom overlaybd config file
Co-authoerd-by: Chen Chen<yuchen.cc@alibaba-inc.com>
Co-authoerd-by: Bowei Zhuang <zhuangbowei.zbw@alibaba-inc.com>
=> add untar with whiteout

src/overlaybd/untar/CMakeLists.txt, src/overlaybd/untar/header.cpp, src/overlaybd/untar/libtar.cpp, src/overlaybd/untar/libtar.h
=> untar: add support for pax format

CMakeLists.txt, README.md, src/config.h, src/example_config/overlaybd.json, src/image_service.cpp, src/image_service.h, src/overlaybd/config_util.h, src/test/CMakeLists.txt, src/test/simple_auth_server.cpp
overlaybd-service can send an http request with remote_url to the speci-
fied server address to get credentials.
see README.md for details
=> Add a new credential mode for lazy-loading

src/overlaybd/lsmt/file.cpp, src/overlaybd/registryfs/registryfs.cpp, src/overlaybd/registryfs/registryfs.h, src/overlaybd/zfile/zfile.cpp
- remove extra logs for lsmt and zfile
- add support for self host storage registry
=> multiple changes

src/image_service.cpp
=> fix background download src

src/overlaybd/lsmt/file.cpp
required for sparse file on xfs
=> truncate for sparse rw data file

src/overlaybd/untar/libtar.cpp
=> untar: fix identifying all-zero EOF mark

src/tools/overlaybd-commit.cpp
=> Add zstd compress options in overlaybd-commit

src/overlaybd/untar/libtar.cpp, src/overlaybd/untar/libtar.h
=> untar: write align

src/overlaybd/untar/libtar.cpp
=> untar: avoid unnecessary follow

.github/workflows/dev-release.yml, CMake/Findrapidjson.cmake, src/overlaybd/zfile/zfile.cpp
=> use newest rapidjson and minor changes

CMakeLists.txt
=> bump to v0.5.3

src/overlaybd/untar/header.cpp, src/overlaybd/untar/libtar.cpp, src/overlaybd/untar/libtar.h
=> untar: fix header get size

src/example_config/overlaybd-tcmu.service
=> fix service

src/overlaybd/zfile/zfile.cpp
=> fix decleration of 'm_ht' in ZFileBuilder

README.md, src/overlaybd/extfs/CMakeLists.txt
Signed-off-by: Bowei Zhuang <zhuangbowei.zbw@alibaba-inc.com>
=> add doc for standalone userspace image-convertor

README.md
=> add "enableThread" description in readme

src/overlaybd/extfs/buffer_file.h, src/overlaybd/extfs/extfs.cpp, src/overlaybd/extfs/test/test.cpp
=> extfs: fulfill unimplemented functions

src/overlaybd/untar/header.cpp
Signed-off-by: Bowei Zhuang <zhuangbowei.zbw@alibaba-inc.com>
=> untar: avoid resolving gname and uname

src/overlaybd/zfile/zfile.cpp
=> Check request range if exceed in ZFile::pread()

src/image_file.cpp, src/overlaybd/registryfs/registryfs.cpp
=> Enhance log

CMakeLists.txt, README.md, src/bk_download.cpp, src/bk_download.h, src/image_file.cpp, src/image_service.cpp, src/overlaybd/cache/CMakeLists.txt, src/overlaybd/cache/cache.cpp, src/overlaybd/cache/cache.h, src/overlaybd/cache/download_cache/CMakeLists.txt, src/overlaybd/cache/download_cache/download_cache.cpp, src/overlaybd/cache/download_cache/thread_range_lock.h, src/overlaybd/cache/frontend/cached_file.cpp, src/overlaybd/cache/frontend/cached_file.h, src/overlaybd/cache/frontend/cached_fs.cpp, src/overlaybd/cache/full_file_cache/cache_pool.cpp, src/overlaybd/cache/full_file_cache/cache_pool.h, src/overlaybd/cache/full_file_cache/test/cache_test.cpp, src/overlaybd/cache/pool_store.h, src/overlaybd/zfile/compressor.cpp, src/overlaybd/zfile/zfile.cpp, src/prefetch.cpp, src/switch_file.cpp, src/switch_file.h
- add new cache mode: download, sharing storage with background download;
- refactor switch file for safety;
- refine prefetch without decompression
=> optimizations for vcpu and bump version v0.6.0

src/overlaybd/registryfs/registryfs.cpp
=> Support HTTPS in accelerate URL

src/main.cpp
=> fix length for write_same

src/overlaybd/gzindex/gzfile.cpp, src/overlaybd/gzindex/gzfile.h, src/overlaybd/gzindex/gzfile_index.h, src/overlaybd/gzindex/gzip_index_create.cpp
Signed-off-by: michael.mk <michael.mk@alibaba-inc.com>
=> add gzindex

src/overlaybd/gzindex/gzfile.cpp, src/overlaybd/gzindex/gzfile_index.h, src/overlaybd/gzindex/gzip_index_create.cpp
enhance index to improve read performance.
=> enhance index

src/overlaybd/gzindex/gzfile.cpp, src/overlaybd/gzindex/gzip_index_create.cpp, src/overlaybd/gzindex/test/test.cpp
- fix bug of using gzip_index with deflate blocks over 64KB in size
- fix ut of gzip_index
- fix offset<0 in gzip_index.pread()
=> fix bug in gz_index

README.md, src/example_config/overlaybd.json, src/overlaybd/tar_file.cpp, src/tools/overlaybd-commit.cpp
support wrapper zfile with tar.
=> overlaybd-commit: support wrapper zfile with tar

src/image_service.cpp, src/tools/overlaybd-apply.cpp, src/tools/overlaybd-commit.cpp, src/tools/overlaybd-create.cpp, src/tools/overlaybd-zfile.cpp
- add default value for flag arg
- new io_alloc in advance.
=> add default value for flag arg, new io_alloc in advance.

CMake/Findphoton.cmake, README.md, src/config.h, src/example_config/overlaybd-registryv2.json, src/example_config/overlaybd.json, src/image_file.cpp, src/image_service.cpp, src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/file.h, src/overlaybd/registryfs/registryfs.cpp, src/test/test.cpp, src/tools/overlaybd-commit.cpp
- support setting uuid in overlaybd-commit
- support config log size, rotate num #186
- log time using localtime #186
=> add some feature

README.md, src/config.h, src/image_file.cpp, src/prefetch.cpp, src/prefetch.h
support config prefetch concurrency
=> trace: support config prefetch concurrency

src/overlaybd/lsmt/file.cpp
Implement function `commit()` for sealed RO file.
=> Implement commit() in LSMTReadOnlyFile

src/tools/overlaybd-apply.cpp
Verify the sha256 checksum of the input file in overlaybd-apply, ensuring the correctness of the input tar/gzip file after untar/uncompression.
=> add sha256 verify for  input file in overlaybd-apply

.github/workflows/release.yml
git tag sort by version in release
Fixes #
=> release: git tag sort by version

src/overlaybd/zfile/zfile.cpp
=> zfile: fix iterator check

src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/format_spec.md, src/overlaybd/zfile/compressor.cpp, src/overlaybd/zfile/compressor.h, src/overlaybd/zfile/format_spec.md, src/overlaybd/zfile/test/test.cpp, src/overlaybd/zfile/zfile.cpp, src/tools/overlaybd-commit.cpp, src/tools/overlaybd-zfile.cpp
Co-authored-by: Huiba Li <lihuiba@gmail.com>
Fixes #
=> Add format spec. for LSMT/ZFile

src/sure_file.cpp
=> fix sure file timeout, sync with tcmu timeout

src/tools/overlaybd-apply.cpp, src/tools/overlaybd-zfile.cpp
Fixes [accelerated-container-image #196](https://github.com/containerd/accelerated-container-image/issues/196)
=> [FIX] zfile validation check should skip tar header

docs/README.md, docs/specs/lsmt.md, docs/specs/zfile.md
add lsmt and zfile specs to docs and pages.
=> update doc for spec

docs/index.html, src/overlaybd/lsmt/format_spec.md, src/overlaybd/zfile/format_spec.md
minor fix for spec doc and pages format
=> minor fix for spec doc and pages format

src/bk_download.cpp, src/image_file.cpp, src/overlaybd/extfs/extfs.cpp, src/overlaybd/tar/libtar.cpp, src/overlaybd/tar/tar_file.cpp, src/overlaybd/tar/whiteout.cpp, src/switch_file.cpp
=> refactor some logs

CMake/Findphoton.cmake
update photon version to v0.6.10 
Fixes #
=> update photon version

src/overlaybd/zfile/zfile.cpp
- add retry for zfile decompression
- fix range check for zfile pread
Fixes #
=> add retry for zfile decompress and fix

CMake/Findphoton.cmake
update photon version to v0.6.12
Fix registry v2 redirection error for some url without path.
=> update photon to v0.6.12

src/overlaybd/cache/full_file_cache/cache_store.cpp
=> [NIT] repeat RLock

src/tools/turboOCI-apply.cpp
support zfile over tar in turboOCI-apply
Fixes #
=> support zfile over tar in turboOCI-apply

CMake/Findphoton.cmake
update photon to v0.6.16
#317 
=> update photon to v0.6.16

.github/workflows/release.yml, .github/workflows/release/build.sh, src/overlaybd/tar/erofs/CMakeLists.txt, src/overlaybd/tar/erofs/liberofs.cpp
Perform code cleanup and make minor fixes.
Fixes #
=> Cleanup and minor fixes

.github/workflows/release.yml
=> build: add release package for ubuntu 24.04
