containerd/overlaybd

CMake/externalBoost.cmake, CMake/externalRapidJSON.cmake, README.md
According to CMake
> Specifying this option is strongly recommended for URL downloads, as it ensures the integrity of the downloaded content. It is also used as a check for a previously downloaded file, allowing connection to the remote location to be avoided altogether if the local directory already has a file from an earlier download that matches the specified hash.
TODO: Add Readme to illustrate how to prepare third-party packages manually, if network got some problems. For instance, behind firewall.
=> Add md5 for external package downloading

src/overlaybd/net/curl.cpp
=> fix compile error of missing include string #18

src/overlaybd/alog.h, src/overlaybd/fs/lsmt/index.cpp, src/overlaybd/utility.h, src/tools/overlaybd-commit.cpp, src/tools/overlaybd-create.cpp
1) WARNING both gcc9/gcc10
```
[ 27%] Linking CXX static library ../../output/libbase_lib.a
/root/wujiaxu/workspace/cpp/overlaybd/src/overlaybd/fs/lsmt/index.cpp: In member function ‘void LSMT::LevelIndex::print_info()’:
/root/wujiaxu/workspace/cpp/overlaybd/src/overlaybd/fs/lsmt/index.cpp:170:30: warning: ‘%lu’ directive writing between 1 and 20 bytes into a region of size between 0 and 255 [-Wformat-overflow=]
170 |             sprintf(msg, "%s %lu ", msg, (*it).size());
|                              ^~~
/root/wujiaxu/workspace/cpp/overlaybd/src/overlaybd/fs/lsmt/index.cpp:170:20: note: ‘sprintf’ output between 4 and 278 bytes into a destination of size 256
170 |             sprintf(msg, "%s %lu ", msg, (*it).size());
|             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
2) …
=> fix some compile error/warning #9

src/image_file.h, src/image_service.cpp, src/main.cpp, src/overlaybd/fs/registryfs/registryfs.cpp, src/overlaybd/fs/registryfs/registryfs.h, src/sure_file.cpp, src/tools/CMakeLists.txt, src/tools/overlaybd-check.cpp, src/tools/overlaybd-info.cpp
Stat when open registryfile, sending a http request, if auth failed, exit and return open failure with 401.
After opened, if auth failed, retry in sure file instead of registryfs.
=> Registyfs only support callback, exit when open if no auth

src/overlaybd/fs/lsmt/test/lsmt-filetest.h
The legacy value in LSMT unit test takes too long.
This commit will reduce time cost of LSMT unit test
=> change default value in unit test

src/prefetch.cpp
When the Prefetcher's destructor is called before `replay`, the `thread_enable_join` will be passed with a nullptr.
So remove the vecotr initialization in constrctor.
=> Fix Prefetcher segment fault in destructor

src/overlaybd/net/curl.h
HeaderMap should able to set each key multiple times,
so redirected response header will keep final rewritten headers,
such as "Content-Type", "Content-Length", etc.
Signed-off-by: Du Rui <coldwings@me.com>
=> Fix curl headermap setting value during redirection

.github/workflows/dco.yml, README.md
Fix repository name to `containerd` instead of `alibaba`.
=> github,README: fix repository name to containerd instead of alibaba

src/overlaybd/fs/zfile/CMakeLists.txt, src/overlaybd/fs/zfile/crc32/README, src/overlaybd/fs/zfile/crc32/crc32c.cpp, src/overlaybd/fs/zfile/crc32/dsa.cpp, src/overlaybd/fs/zfile/crc32/dsa.h, src/overlaybd/fs/zfile/crc32/idxd.h, src/overlaybd/fs/zfile/crc32/libaccel_config.h, src/overlaybd/fs/zfile/test/test.cpp
Intel® DSA is a high-performance data copy and transformation accelerator that will be integrated into future Intel® processors, targeted for optimizing streaming data movement and transformation operations common with applications for high-performance storage, networking, persistent memory, and various data processing applications.
Intel® DSA replaces the Intel® QuickData Technology, which is a part of Intel® I/O Acceleration Technology.
The goal is to provide higher overall system performance for data mover and transformation operations while freeing up CPU cycles for higher-level functions. Intel® DSA enables high-performance data mover capability to/from volatile memory, persistent memory, memory-mapped I/O, and through a Non-Transparent Bridge (NTB) device to/from remote volatile and …
=> Calculate CRC using Intel DSA

src/overlaybd/fs/zfile/CMakeLists.txt
Not compile dsa.cpp when dsa is not enabled.
@hhb584520
=> fix DSA CMake

README.md
While working on a ubuntu 21 server and compile the project,
a compliation warning occured.
/root/git_repo/overlaybd/src/overlaybd/fs/cache/ocf_cache/test/ocf_perf_test.cpp:6:10: fatal error: gflags/gflags.h: No such file or directory
6 | #include <gflags/gflags.h>
|          ^~~~~~~~~~~~~~~~~
compilation terminated.
Signed-off-by: Changwei Ge <chge@linux.alibaba.com>
=> readme: add one more suggested library dependency

src/overlaybd/fs/lsmt/file.cpp, src/overlaybd/fs/lsmt/file.h, src/overlaybd/fs/lsmt/test/CMakeLists.txt, src/overlaybd/fs/lsmt/test/lsmt-filetest.h, src/overlaybd/fs/lsmt/test/test.cpp
Overlaybd supports writable layer by append-only mode. Continuous
data writing will generate a lot of garbage, making the disk usage
uncontrollable.
In this commit, we use Linux sparse file as another writable layer
mode to control disk usage precisely.
=> Support sparse file as overlayBD writable layer

src/overlaybd/fs/lsmt/test/lsmt-filetest.h, src/overlaybd/fs/lsmt/test/test.cpp, src/overlaybd/fs/zfile/zfile.cpp, src/overlaybd/fs/zfile/zfile.h
ZFileWriter is an extension class in ZFile which compresses the buffer received
from write() function. Benefit from this, LSMTFile::commit() can generate a
ZFile without saving temporary file.
=> Support stream writer in ZFile

src/overlaybd/zfile/compressor.cpp, src/overlaybd/zfile/compressor.h, src/overlaybd/zfile/lz4/lz4-qat.c, src/overlaybd/zfile/lz4/lz4-qat.h
1.Add ICompressor::batch_decompress() to support QAT
2.ZFile will use batch decompress by default.
Accelerate compression to provide improved efficiency, scalability and
performance. Intel QuickAssist Technology (Intel QAT) offloading
Compression from CPU which can save cycles, time and space.
As the complexity of applications continues to grow, systems need more
and more computational resources for workloads, including cryptography
and data compression.
The drivers and patches offered here assist application developers to
take advantage of Intel® QuickAssist Integrated Accelerator that is
offered with platforms based on Intel® processors.
To Learn how to use Intel® QuickAssist Technology and run example code,
review our tutorial videos on Intel Developer Zone – Intel® QuickAssist …
=> ZFile support batch decompress

.github/workflows/cmake.yml, CMakeLists.txt, README.md, src/image_service.cpp, src/overlaybd/zfile/CMakeLists.txt, src/overlaybd/zfile/compressor.cpp, src/overlaybd/zfile/test/test.cpp, src/overlaybd/zfile/zfile.cpp, src/tools/overlaybd-zfile.cpp
#125 
- add ZSTDCompressor
- refactoring ZFile
- in cli-tool `overlaybd-zfile`, add `--algorithm` and `--bs` option
=> support `zstd` in ZFile compression

.github/workflows/cmake.yml
Fixes error in #131
```
In file included from /home/runner/work/overlaybd/overlaybd/googletest-release-1.10.0/googletest/src/gtest-all.cc:42:
/home/runner/work/overlaybd/overlaybd/googletest-release-1.10.0/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
/home/runner/work/overlaybd/overlaybd/googletest-release-1.10.0/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
1301 |   StackLowerThanAddress(&dummy, &result);
|   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/runner/work/overlaybd/overlaybd/googletest-release-1.10.0/googletest/src/gtest-death-test.cc:1290:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared …
```
=> Update Googletest to v1.11.0

src/tools/overlaybd-commit.cpp
If `block_size` is uninitialized, [this statement](https://github.com/containerd/overlaybd/commit/19f38b11a78df7b9919a8311a6b473200c4bb350#diff-abe1d8f469f69ca05d542c840c37206b8ecdd1323acc9995ea30dc6d7cbe899bR94-R96) may not work.
=> Fix uninitialized integer in overlaybd-commit

.github/workflows/cmake.yml, .github/workflows/dev-release.yml, CMake/Findext2fs.cmake, README.md, src/overlaybd/CMakeLists.txt, src/overlaybd/extfs/CMakeLists.txt, src/overlaybd/extfs/buffer_file.h, src/overlaybd/extfs/extfs.cpp, src/overlaybd/extfs/extfs.h, src/overlaybd/extfs/extfs_io.cpp, src/overlaybd/extfs/extfs_utils.h, src/overlaybd/extfs/test/CMakeLists.txt, src/overlaybd/extfs/test/test.cpp, src/tools/CMakeLists.txt, src/tools/overlaybd-apply.cpp
overlaybd-apply could be used with [accelerated-container-image](https://github.com/containerd/accelerated-container-image) to convert an image from traditional OCI tarball format to overlaybd format.
Co-authored-by: Lanzheng Liu <lanzheng.liulz@alibaba-inc.com>
Co-authored-by: Chen Chen <yuchen.cc@alibaba-inc.com>
Signed-off-by: Bowei Zhuang <zhuangbowei.zbw@alibaba-inc.com>
=> add overlaybd-apply and extfs for image conversion in user mode

.github/workflows/cmake.yml, CMake/Findphoton.cmake, CMake/Findrapidjson.cmake, README.md, src/config.h, src/example_config/overlaybd-registryv2.json, src/image_file.h, src/image_service.cpp, src/main.cpp, src/overlaybd/registryfs/registryfs.h, src/overlaybd/registryfs/registryfs_v2.cpp, src/prefetch.cpp
registryfs v2 is based on photon http client instead of libcurl.
Add `registryFsVersion: "v2"` to /etc/overlaybd/overlaybd.json to enable it.
=> Add registryfs v2

src/config.h, src/image_service.cpp, src/main.cpp, src/overlaybd/cache/ocf_cache/ease_bindings/env/ocf_env.h, src/overlaybd/cache/ocf_cache/ease_bindings/queue.cpp, src/overlaybd/registryfs/registryfs.cpp
When "enableThread" option is set to "true" in overlaybd.json, overlaybd device will work in thread mode. 
It benifits when multiple overlaybd devices are running concurrently and CPU has idle cores.
Pay attention that it only works with "ocf" cache ("cacheType" should be "ocf") currently. File cache doesn't have supported multi-thread yet.  
=> enable obd dev work in thread

README.md, src/config.h, src/example_config/overlaybd-registryv2.json, src/example_config/overlaybd.json, src/image_service.cpp, src/main.cpp, src/overlaybd/cache/ocf_cache/ease_bindings/ctx.h, src/overlaybd/cache/ocf_cache/ease_bindings/volume.cpp, src/overlaybd/cache/ocf_cache/ocf_cache.cpp
Group cache configs, open refill size config. Compatible with old formats.
Enable ocf cache audit.
See README.md for details
=> config: optimize cache config

src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/file.h, src/overlaybd/lsmt/index.h, src/overlaybd/lsmt/test/lsmt-filetest.h, src/overlaybd/lsmt/test/test.cpp, src/tools/overlaybd-commit.cpp
This PR contains two key features:
- __LSMTWarpfile__
A new LSMT format that contains the target file index but does not contain any content
- __Dolls:__
Support multiple sub-LSMTReadOnlyFiles like a 'Dolls'
LSMTReadOnlyFile
|
m_files[0]--IFile
|
m_files[1]--LSMTReadOnlyFile
|                     |
m_files[2]--IFile     m_files[0]--LSMTReadOnlyFile
|                     |
m_files[3]            m_files[1]--IFile
|                     |
...                   ...
=> New Features: LSMTWarpfile & Dolls

src/CMakeLists.txt, src/image_service.cpp, src/test/CMakeLists.txt, src/test/test.cpp
- Change to on-demand download while p2p accelerate_url invalid
- Add a unit test for p2p failover.
=> Add failover for p2p download

src/overlaybd/untar/libtar.cpp, src/tools/overlaybd-create.cpp
- overlaybd-create: variable of flag `--fastoci` is not given initial values
- extract_regfile_meta_only: we found the size of extents of some files could be larger than 512 when working with fastoci convertion.
=> fix bug of overlaybd-create, untar_meta_only

src/image_file.cpp
TargetDigest is required to use gzip cache, but not for fastoci.
=> disable gzip cache when targetDigest is not set

src/image_file.cpp, src/main.cpp, src/prefetch.cpp
- support replay when trace file is set, and not empty.
- move prefetch file outside to enable trace record when using local blobs.
=> trace: support replay with trace file

.github/workflows/cmake.yml, .github/workflows/dev-release.yml
Add e2e test for FastOCI:
- download a FastOCI meta image
- create a TCMU block device
- mount to a directory and show image content
Update workflow environment to Ubuntu-22.04:
- the Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023, [here for more details](https://github.com/actions/runner-images/issues/6002)
=> Add e2e test for FastOCI & Update workflow environment to Ubuntu-22.04

README.md, src/example_config/overlaybd-registryv2.json, src/example_config/overlaybd.json
In `overlaybd.json`, the format of `p2pConfig.address` is `localhost:<P2PConfig.Port>/<P2PConfig.APIKey>`, depending on `dadip2p.yaml`.
If using default `dadip2p.yaml` in [dadi-p2proxy](https://github.com/data-accelerator/dadi-p2proxy), `overlaybd.json` should be
```json
{
...
"p2pConfig": {
"enable": true,
"address": "localhost:19145/dadip2p"
}
...
}
```
=> make p2pConfig compatible with data-accelerator/dadi-p2proxy

src/bk_download.cpp, src/bk_download.h, src/image_file.cpp, src/image_file.h, src/tools/overlaybd-commit.cpp
After `close_seal()` in overlaybd-commit, we can open this layer as a RO file. This has an accelerating effect on image construction, we can seal it in build, and compress it to Zfile in image push.
=> support lsmt seal and commit sealed

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yaml, .github/PULL_REQUEST_TEMPLATE.md
The change provides the guidance for contributors to open issue and pr.
=> chore: add issue and pr templates

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml
=> fix: typo in bug template

.github/workflows/release/build.sh
Release building: fix certificate error when wget cmake in centos 8
`ERROR: The certificate of 'cmake.org' is not trusted.`
Add flag `--no-check-certificate` for `wget`
=> fix certificate error when wget cmake

src/bk_download.cpp, src/bk_download.h, src/image_file.cpp
fix race condition in bk_download verify, which may cause overlaybd-tcmu hang.
=> fix race condition in bk_download verify;

.github/workflows/cmake.yml, CMake/Findext2fs.cmake, src/overlaybd/extfs/CMakeLists.txt, src/overlaybd/extfs/extfs.h, src/overlaybd/extfs/mkfs.cpp, src/tools/overlaybd-apply.cpp, src/tools/overlaybd-create.cpp
add mkfs for extfs and overlaybd-apply/create
- add a simple mkfs implementation with specific parameters
- produce reproducible result with fixed uuid and hash seed
- add --mkfs flag for overlaybd-apply/create, which do mkfs before apply data / after create
=> add mkfs for extfs and overlaybd-apply

src/bk_download.cpp
fix bug in background download when bk_downloa thread is interrupt while verify thread still running.
=> bk_download: wait verify finish

src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/test/test.cpp
- close_seal() Method can also convert a LSMTSparseFile as a LSMTReadOnlyFile with 'sparse_rw' tag. Users should be careful to compact such files before uploading them. :D
- And also, a compacted LSMTReadonlyFile shouldn't be committed twice. This PR adds some format check for it.
https://github.com/containerd/overlaybd/discussions/216
=> [Feat] LSMTSparseFile support close_seal()

CMakeLists.txt, src/bk_download.cpp, src/overlaybd/cache/download_cache/download_cache.cpp, src/overlaybd/cache/ocf_cache/CMakeLists.txt, src/overlaybd/cache/ocf_cache/ocf_cache.cpp, src/overlaybd/extfs/extfs.cpp, src/overlaybd/lsmt/file.cpp, src/overlaybd/registryfs/registryfs.cpp, src/overlaybd/registryfs/registryfs_v2.cpp, src/overlaybd/tar/libtar.cpp, src/overlaybd/tar/tar_file.cpp, src/overlaybd/zfile/compressor.cpp, src/overlaybd/zfile/lz4/lz4-qat.c, src/overlaybd/zfile/zfile.cpp
- fix useless pread return value check in zfile jump table loading
- fix other sign-cmpare warnings
Fixes  https://github.com/containerd/accelerated-container-image/issues/205
=> fix all sign-compare warnings

README.md, src/bk_download.cpp, src/bk_download.h, src/config.h, src/image_file.cpp, src/main.cpp, src/sure_file.cpp
add a configuration `downlaod.blockSize` for background download;
add audit log for background download;
fix some compling warnings;
Fixes #
=> add bk_download bs config, audit; fix some warning

src/overlaybd/zfile/test/test.cpp, src/overlaybd/zfile/zfile.cpp, src/overlaybd/zfile/zfile.h, src/tools/overlaybd-zfile.cpp
overlaybd-zfile --verify <file> will check if the specified file is a valid zfile with checksum.
https://github.com/containerd/accelerated-container-image/issues/196
Fixes #
=> Add '--verify' flag in overlaybd-zfile

src/overlaybd/zfile/compressor.cpp, src/overlaybd/zfile/zfile.cpp
Add return value check for Zfile::BlockReader to avoid getting invalid data in ZFile::pread.
Fixes #
=> Add error status in ZFile::BlockReader

src/tools/overlaybd-commit.cpp
Fixed branch bug in overlaybd-commit. In fastoci conversion, it will go to a wrong branch because missing of `else`.
Fixes #
=> fix bug in overlaybd-commit for fastoci

src/overlaybd/zfile/zfile.cpp, src/tools/CMakeLists.txt, src/tools/overlaybd-apply.cpp, src/tools/overlaybd-commit.cpp, src/tools/overlaybd-create.cpp, src/tools/overlaybd-zfile.cpp
- zfile: always try evict after loading jump table failed
- tools: add verbose option and photon::fini()
- 
Fixes #
=> fix for zfile and tools

src/image_service.cpp, src/image_service.h, src/test/CMakeLists.txt, src/test/image_service_test.cpp
Before this change:
- if `p2pConfig().enable() == true`, then `srcfs` will equal `remote_fs`, which leads to double free.
- if `check_accelerate_url` failed, it doesn't use any cache, this will cause all data to back to the source, resulting in reduced efficiency.
Fixes #
=> fix double free & enhence p2p failover

CMake/Findrapidjson.cmake, src/image_service.cpp, src/overlaybd/cache/gzip_cache/cached_fs.h, src/tools/overlaybd-apply.cpp
ensure overlaybd-apply exit normally: fix destruction of image service and gzip cache fs.
Fixes https://github.com/containerd/accelerated-container-image/issues/212
=> ensure overlaybd-apply exit normally

src/overlaybd/tar/header.cpp, src/overlaybd/tar/libtar.cpp, src/overlaybd/tar/libtar.h, src/overlaybd/tar/test/CMakeLists.txt, src/overlaybd/tar/test/test.cpp, src/tools/CMakeLists.txt, src/tools/comm_func.cpp, src/tools/comm_func.h, src/tools/fastoci-apply.cpp, src/tools/overlaybd-apply.cpp
- export tar meta from a tar(.tgz) file.
- import tar meta to apply a overlaybd layer.
Tar Meta is a little different from original Tar Header, which
contains the logical offset of data written to the overlaybd.
A stand-alone tool of fastoci that can export/import tar(.gz) meta separately, making fastoci more flexible.
Fixes #
=> [Feat] A stand-alone tool of fastoci:

.github/workflows/cmake.yml, src/image_file.cpp, src/overlaybd/tar/libtar.cpp, src/overlaybd/tar/test/test.cpp, src/tools/CMakeLists.txt, src/tools/comm_func.cpp, src/tools/overlaybd-apply.cpp, src/tools/overlaybd-commit.cpp, src/tools/overlaybd-create.cpp, src/tools/turboOCI-apply.cpp
this issue is related to accelerated-container-image#218
[#218](https://github.com/containerd/accelerated-container-image/issues/218)
=> Rename 'FastOCI' as 'OverlayBD - Turbo OCIv1'

src/overlaybd/lsmt/file.cpp, src/overlaybd/registryfs/registryfs.cpp, src/overlaybd/tar/tar_file.cpp, src/overlaybd/zfile/zfile.cpp, src/switch_file.cpp, src/tools/overlaybd-zfile.cpp
=> enhance tar/zfile checking

src/image_file.cpp, src/overlaybd/zfile/zfile.cpp, src/switch_file.cpp
fix bug in retry open zfile, move new_tar_file_adaptor out of new_switch_file.
Fixes #256 
=> fix bug in retry open zfile

src/overlaybd/tar/tar_file.cpp, src/overlaybd/zfile/zfile.cpp
1. Return value of building zfile jump table is not checked, dirty data may load into jump table;
2. Retry building jump table doesn't work;
3. Zfile trim has defect due to tar_file not implementing fallocate;
=> Fix bugs in zfile evict and build jump table.

src/overlaybd/registryfs/registryfs_v2.cpp
Fix bug within registryfs_v2. `actual_info->info` already contains the prefix "bearer", and this will result in `"bearer bearer ..."`.
When overlaybd's configuration field `registryFsVersion` has a value of `v2` and works with the self-storage registry, this bug occurs and results in a 401 error for on-demand requests.
Fixes #
=> [bugfix] duplicate bearer

src/overlaybd/zfile/zfile.cpp
enhance bound check on building jumptable to avoid unexpected behavior in pread.
=> [bugfix] enhance bound check on building jumptable

src/overlaybd/zfile/format_spec.md, src/overlaybd/zfile/test/test.cpp, src/overlaybd/zfile/zfile.cpp
Since there is unexpected behavior if incorrect data gets during the process of zfile loading, we should add a digest of header/trailer and index to make the dirty data can be evicted.
releated issues: #253 #254  #255 #261 
=> save digest of zfile's header/trailer and index

src/overlaybd/zfile/zfile.cpp
Make ZFile checksum more eye-catching
=> print digest and index checksum in ZFile log

CMake/FindCURL.cmake, CMakeLists.txt
OverlayBD works with libcurl, using some  features that only support in certain version of libcurl.
This patch make it able to build libcurl with source and link the static library, as default.
Fixes #266 by build libcurl 7.42.1 and link static lib.
=> build overlaybd using static compiled libcurl 7.42.1

src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/test/lsmt-filetest.h, src/overlaybd/lsmt/test/test.cpp
UUID is missed when using overlaybd-commit with the option `--uuid` and `--turboOCI`, instead of a random uuid in the committed file. After this fix, we can reproduce turboOCI files.
Fixes #
=> [bugfix] turboOCI commit with uuid

.github/workflows/release/build.sh, CMake/FindCURL.cmake
The static libcurl build procedure needs autoconf, automake and libtool in system, add dependency installing step for publish build scrilp.
To unify static libcurl dependencies, disabled features that do not used in overlaybd.
Fixes #266 
=> fix workflow release dependencies

src/image_file.cpp
fix segfault when failed to open remote layer for image with acceleration layer
Fixes #
=> fix segfault in open lower

CMake/FindCURL.cmake, CMake/FindOpenSSL.cmake, CMake/Findphoton.cmake, CMakeLists.txt, README.md
Changes default compile option as do not build with static libcurl/openssl, to keep binaries acts like before.
In last fix, static libcurl still using shared linked libssl & libcrypto. Since current distributed OS default openssl version are
usually using version higher than 1.1.0，that old libcurl version can not recognize it, will prevent libcurl enabling https feature.
Whole static openssl building makes those dependencies using static build openssl 1.0.2k.
Related CMake options document has been added in README.md
Fixes #
=> build static openssl when building static libcurl

CMake/Findphoton.cmake, README.md, src/config.h, src/overlaybd/registryfs/registryfs.h, src/overlaybd/registryfs/registryfs_v2.cpp
- use registryfs version v2 as default, which is based on PhotonLibOS http client module. registryfs v2 performs much faster then v1(libcurl based).
- add registry uploader in registryfs v2 which can used in image conversion.
Fixes #
=> update regitsryfs v2 and use v2 as default

src/overlaybd/zfile/compressor.h, src/overlaybd/zfile/test/test.cpp, src/overlaybd/zfile/zfile.cpp, src/tools/overlaybd-commit.cpp
Increase zfile compression speed by utilizing multi-core parallelism.
Fixes #
=> multi-processor zfile builder

src/overlaybd/extfs/mkfs.cpp
Fixed the problem of disk space being incorrectly reported as full due to the incorrect status of inode1 in lower version Linux kernel.
Fixes https://github.com/containerd/accelerated-container-image/discussions/238
=> fix mkfs by marking inode 1

src/overlaybd/extfs/test/test.cpp, src/tools/overlaybd-create.cpp
1. overlaybd-create support create raw image (test use);
2. extfs test use make_extfs instead of mkfs.ext4;
Fixes #
=> support create raw image, extfs test use make_extfs

src/overlaybd/lsmt/file.cpp, src/tools/overlaybd-create.cpp
Add support for vsize = 0 to overlaybd-create indicating that the vsize is inherited from the lower layers.
Fixes #
=> Add support for vsize = 0 to overlaybd-create

src/overlaybd/registryfs/registryfs_v2.cpp
=> registry: enhanced error handling

src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/file.h
update vsize and rewrite header for lsmt rw layer with zero vsize, which means inherit the vsize of lower, when lstm stack files.
After this change, the result of lsmt committed files remain consistent with the previous version.
Fixes #
=> update vsize when lsmt stack files if needed

src/overlaybd/stream_convertor/stream_conv.cpp
Fix include path in stream_conv to be compatible with gcc6.5.1
=> replace 'string_view.h' to 'photon/common/string_view.h'

src/overlaybd/tar/header.cpp, src/overlaybd/tar/libtar.cpp, src/overlaybd/tar/libtar.h, src/overlaybd/tar/tar_file.cpp, src/overlaybd/tar/test/test.cpp
support userspace convertor run with non-root privileges.
Fixes #
=> untar: optional checking euid

CMake/Findphoton.cmake, CMakeLists.txt, README.md, src/config.h, src/image_service.cpp, src/main.cpp, src/overlaybd/base64.h, src/overlaybd/registryfs/registryfs.cpp, src/overlaybd/registryfs/registryfs.h, src/overlaybd/registryfs/registryfs_v2.cpp, src/tools/CMakeLists.txt, src/tools/overlaybd-apply.cpp, src/tools/overlaybd-commit.cpp
- [bugfix] libcurl->set_user_passwd(...) may cause basic and bearer auth coexist when the registry's authentication domain name is the same as the registry's domain name (e.g. hub.docker.com/auth/...)
- disable huge page
- cmake 3.15 -> 3.14
- [feat] supports SSL/TLS client certs
- [feat] overlaybd-apply: streaming download and apply
- [feat] overlaybd-commit: streaming zfile compress and upload. This is unavailable with option `-t` because it only supports write-in-sequence, but we have to overwrite the tar header.
Fixes #
=> minor fixes & tools improvements

src/overlaybd/tar/libtar.cpp, src/overlaybd/tar/libtar.h, src/overlaybd/tar/test/test.cpp
It happens that '/' (root dir) exists in some image tarball layer. It will cause userspace convertor failed.
Now, '/' is ignored.
Add a test case for clean_name().
Fixes #
=> untar: ignore '/' in tarball

src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/file.h, src/overlaybd/lsmt/index.cpp, src/overlaybd/lsmt/index.h, src/overlaybd/zfile/zfile.cpp
- add some method for lsmt
- rename crc32c for zfile, to reduce the potential for confusion caused by the name.
- 
Fixes #
=> add some method for lsmt, rename crc32c for zfile

src/overlaybd/zfile/test/test.cpp, src/overlaybd/zfile/zfile.cpp, src/tools/overlaybd-zfile.cpp
Currently, overlaybd-zfile cli only supports local files as a source.
This PR will support STDIN as a source for overlaybd-zfile cli. (eg. cat $file | ./overlaybd-file $out)
Moreover, decompression can't use stdin or pipe as a source since the ZFile index is saved at the end of the file
Fixes #
=> support stdin as source for ZFile compression

src/overlaybd/tar/libtar.cpp
Move store dirs into extract_file. (Directory mtimes must be handled at the end to avoid further file creation in them to modify the directory mtime)
This move will avoid aufs whiteout files (.wh..wh.aufs, .wh..wh.orph/, .wh..wh.plnk/) from creating and setting attributes.
Fixes #
=> untar: mv store dirs into extract_file

src/bk_download.h
**What this PR does / why we need it**: Fixes a compilation error I get when building on Arch Linux. The numeric types (e.g. uint64_t) are defined in `<cstdint>` and the header file needs to be included.
=> Fix build on Arch Linux

src/switch_file.cpp
This may cause the read requests from overlaybd device wrong after the switch_file is switched (i.e. after the background download is done).
Fixes #
=> [bugfix] switch file

src/overlaybd/tar/tarerofs.cpp, src/overlaybd/tar/tarerofs.h, src/tools/turboOCI-apply.cpp
Currently erofs-utils is integrated into overlaybd by using `mkfs.erofs` executable file.  It's not optimial since raw data needs to be dumped first and output data needs to be write into overlaybd then.
Later API integration may be a better form but it needs more work.
The corresponding accelerated-container-image PR:
https://github.com/containerd/accelerated-container-image/pull/272
The corresponding erofs-utils for test can be found at:
git clone https://gitee.com/anolis/erofs-utils.git -b overlaybd-dev
Fixes #
=> add support for tarerofs for TurboOCI

src/overlaybd/tar/tarerofs.cpp, src/overlaybd/tar/tarerofs.h, src/tools/turboOCI-apply.cpp
Fix EROFS support of TurboOCI-apply when applying multiple layers:
- Correct the bottom layer check;
- Fix up pread() alignment issue.
Fixes #
=> Fix EROFS support of TurboOCI-apply

src/overlaybd/registryfs/registryfs_v2.cpp
Some container registries use just Basic auth to fetch images, instead of the Bearer token flow
=> Support container registries using Basic Auth

CMake/Findphoton.cmake, README.md, src/config.h, src/example_config/overlaybd.json, src/image_service.cpp, src/main.cpp, src/overlaybd/registryfs/registryfs.cpp, src/overlaybd/registryfs/registryfs.h, src/overlaybd/registryfs/registryfs_v2.cpp, src/test/image_service_test.cpp, src/version.h
support customized UA to  identify traffic or something else.
Fixes #328 
=> Customized HTTP useragent support:

src/overlaybd/tar/erofs/CMakeLists.txt, src/overlaybd/tar/erofs/liberofs.cpp, src/overlaybd/tar/erofs/liberofs.h, src/tools/turboOCI-apply.cpp
So that `turboOCI-apply --import` can be used.
Fixes #
=> Support Tar metaidx for EROFS

src/overlaybd/tar/erofs/CMakeLists.txt, src/overlaybd/tar/erofs/liberofs.cpp
Set the minimum inline xattr size for the root directory of the base layer, as there may not be enough room for xattr during the incremental build process.
Fixes #
=> [EROFS] Add support for xattr reservation of the base layer rootdir

README.md, src/CMakeLists.txt, src/image_file.cpp, src/image_file.h, src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/file.h, src/prefetch.cpp, src/prefetch.h, src/test/CMakeLists.txt, src/test/trace_test.cpp
DynamePrefetcher allows users to pass a filelist through the label 'containerd.io/snapshot/overlaybd/record-trace-path' to prefetch the files during container startup.
Fixes #
=> [feat.] DynamicPrefetcher

src/overlaybd/tar/erofs/CMakeLists.txt
This PR is a tiny change to move the erofs dependency from using the git protocol to https. The main reasoning behind it is to better support builds behind firewalls which have become more and more strict in recent times as security pushes happen. We have encountered such issues where firewalls restrict ports other than 443 and 80 for security but using the git protocol uses 9418.
Fixes #
=> Switch erofs endpoint to use https

.github/workflows/release/build.sh, CMakeLists.txt, src/overlaybd/zfile/CMakeLists.txt
In the release workflow, we are using gcc 8.5.1 on centos8, which can be problematic for compiling the arm64 binary. We should use gcc 9.2.1 instead.
Fixes #
=> fix arm build

src/image_file.cpp
The DynamicPrefetcher::replay(IFile* imgfile) progress is running in a background thread and it will access an invalid pointer after *imgfile  has been deleted in stack_files() 
https://github.com/containerd/overlaybd/blob/7093da0f29da0d3b1dc786f404fbf87c875c366d/src/overlaybd/lsmt/file.cpp#L1790
Fixes #
=> [Fix] access deleted point in prefetch thread.

src/image_file.cpp, src/image_file.h, src/image_service.h, src/overlaybd/lsmt/file.cpp, src/overlaybd/lsmt/file.h, src/overlaybd/lsmt/index.cpp, src/overlaybd/lsmt/index.h, src/overlaybd/lsmt/test/test.cpp, src/overlaybd/zfile/zfile.cpp, src/tools/CMakeLists.txt, src/tools/overlaybd-merge.cpp
We are providing a tool named 'overlaybd-merge' that can compact an overlaybd image with multiple layers into a single layer.
And replacing a single read for ZFile index with parallel loading.
Fixes #345 
=> [feat.] a new tool 'overlaybd-merge'

src/overlaybd/tar/erofs/liberofs.cpp, src/overlaybd/tar/erofs/liberofs.h, src/prefetch.cpp, src/test/trace_test.cpp, src/tools/comm_func.cpp, src/tools/comm_func.h
1. Remove the global variables `_target` and `_source`, and introduce `struct liberofs_file` to wrap the source and target files.
2. Introduce prefetch feature.
The corresponding accelerated-container-image PR:
https://github.com/containerd/accelerated-container-image/pull/299
Fixes #
=> [EROFS]: cleanup and introduce prefetch feature

MAINTAINERS
Hi guys~  
These developers have contributed lots of code and proposals to this project. I would like to invite them as project maintainers:
- invite @salvete as a committer
_Luo is the core developer responsible for supporting EROFS on overlaybd, having implemented numerous features for overlaybd based on the mainline kernel-erofs and erofs-utils._
- invite @hsiangkao as a reviewer.
_Gao is the author of EROFS and has also proposed numerous reviews for its integration with OverlayBD._
Needs explicit LGTM from @hsiangkao @salvete  and 1/3 of the **'overlaybd'** Committers.
according to https://github.com/containerd/project/blob/main/GOVERNANCE.md :
> After a candidate has been informally proposed in the maintainers forum, the
existing maintainers are given seven days to discuss the …
=> Update maintainer list

src/overlaybd/lsmt/file.cpp, src/overlaybd/tar/erofs/CMakeLists.txt, src/overlaybd/tar/erofs/test/CMakeLists.txt, src/overlaybd/tar/erofs/test/test.cpp
Workaround if some SegmentMapping refers to end of tar (because the mapping doesn't record real remote mapping size), which could happen on EROFS meta indexes.
Fixes #
=> [bugfix] workaround if some SegmentMapping refers to end of tar

src/overlaybd/tar/erofs/CMakeLists.txt, src/overlaybd/tar/erofs/liberofs.cpp
The inconsistency in the default block sizes between OverlayBD and EROFS can lead to issues during segment mapping. This patch aligns with the block size of overlaybd for mapping (i.e., OverlayBD's 512-byte size) to overcome this inconsistency.
Fixes #
=>  Align with the block size of overlayBD

src/overlaybd/tar/erofs/CMakeLists.txt, src/overlaybd/tar/erofs/liberofs.cpp
Currently, the uid and gid in the tar file are
lost because the `c_uid` and `c_gid` of `erofs_cfg` are not set to -1.
This patch fixes it.
Fixes #
=> [EROFS] fix the loss of uid and gid

src/overlaybd/tar/erofs/erofs_fs.cpp, src/overlaybd/tar/erofs/erofs_fs.h, src/overlaybd/tar/erofs/test/CMakeLists.txt, src/overlaybd/tar/erofs/test/erofs_simple.cpp, src/overlaybd/tar/erofs/test/erofs_stress.cpp, src/overlaybd/tar/erofs/test/erofs_stress_base.cpp, src/overlaybd/tar/erofs/test/erofs_stress_base.h
Add stress testing for EROFS, including:
- file contents
- xattrs
- mode
- uid/gid
- others
Fixes #
=> Add stress test for erofs

src/image_file.cpp, src/image_file.h, src/overlaybd/gzindex/gzfile.cpp, src/prefetch.cpp
- Prefetcher should use the readonly lower_file but not the m_file, or some error will occur when using upper layer and dynamic prefetcher together.
- Fix the way to resolve filepath, now we could use '/' as a prefetch item.
Fixes #
=> fix and enhance dynamic prefetcher

.github/workflows/project-checks.yml, .github/workflows/release.yml, src/image_file.cpp, src/image_file.h, src/overlaybd/lsmt/file.cpp, src/overlaybd/tar/erofs/test/erofs_stress_base.cpp
- fix CI
- artifact actions v3 has been deprecated, so we have to migrated to v4.
- project checks v1.1.0 is no longer work but v1.2.0 is not available for c++ projects (v1.2.0 does go-licenses check ...).
- fix arm build, see also https://github.com/tonistiigi/binfmt/issues/215.
- fix upper layer bug: some error occured when using upper layer. 
- When using dynamic prefetcher with RW mode (have both lower and upper), the prefetcher will be failed to read from lower.
- When using some image_file with upper only, overlaybd could be segfault.
Fixes #
=> Fix CI & upper layer bug

CMakeLists.txt
It was always fetching yaml-cpp, even when it was installed system-wide.
=> Fix yaml-cpp dependency, as it is installed with that name, not yamlcpp
